---
- hosts: moodle-host
  become: yes
  vars:
    nginx_vhosts:
      - server_name: "test.dev"
        root: "/var/www/test"
                    
  vars_files:
    - vars/main.yml
    - vars/vault.yml
    - vars/var_mariadb.yml
        
  roles:
  - role: ansible-role-repo-epel
    when: ansible_os_family == 'RedHat'
  - role: ansible-role-php-versions
    when: ansible_os_family == 'Debian'
  - role: ansible-role-php
  - role: ansible-role-nginx
  - role: ansible-role-mariadb

  
