---
- hosts: all
  become: yes
#  vars:
#    nginx_vhosts:
#      - server_name: "test.dev"
#        root: "/var/www/test"

  vars_files:
    - vars/main.yml
    - vars/vault.yml
    - vars/var_mariadb.yml

  roles:
  - role: geerlingguy.repo-epel
    when: ansible_os_family == 'RedHat'
  - role: geerlingguy.php-versions
#    vars:
#      php_version: '8.2'
#    when: ansible_os_family == 'Debian'
    tags:
      - web
  - role: geerlingguy.php
    vars:
      php_executable: "php8.2"
      php_enablerepo: "remi-php82"
      php_webserver_daemon: "nginx"
      ###    php-fpm
      php_enable_php_fpm: true
      php_fpm_state: started
      php_fpm_enabled_on_boot: true
      ###    php.ini settings
      php_use_managed_ini: true
      php_memory_limit: "128M"
      php_max_execution_time: "90"
      php_upload_max_filesize: "256M"
      php_date_timezone: "Europe/Kyiv"
    tags:
      - web
  - role: geerlingguy.nginx
    vars:
      nginx_listen_ipv6: true
      nginx_vhosts: [demo.site]
      nginx_vhost_template: "vhost.j2"
      nginx_service_state: started
      nginx_service_enabled: yes
    tags:
      - web
  - role: bertvv.mariadb
    tags:
      - db