- src: geerlingguy.repo-epel
  version: 3.1.1
  when: ansible_os_family == 'RedHat'
  
- src: geerlingguy.php-versions
  version: 6.0.0

- src: geerlingguy.php
  version: 4.8.0

- src: geerlingguy.nginx
  version: 3.1.4

- src: bertvv.mariadb
  version: v3.1.3