---
- hosts: all
  become: yes
  vars:
    - nginx_root_dir: "/var/tmp/demo/"
  tasks:
  - name: Check if www moodle directory exists and is not empty
    stat:
      path: "{{ nginx_root_dir }}"
    register: dir_status

#  - name: print debug - dir is not empty
#    debug:
#      msg: "dir {{ nginx_root_dir }} is not empty. Original msg- dir_status"
    #when: dir_status.stat.exists and dir_status.stat.isdir and dir_status.stat.size > 0
#    when: dir_status.stat.exists == true #and dir_status.matched > 0

#  - name: print about empty dir
#    debug:
#      msg: "dir {{ nginx_root_dir }} empty. Original msg- dir_status"
    #when: dir_status.stat.exists and dir_status.stat.isdir and dir_status.stat.size > 0
#    when: not dir_status.stat.exists == 0

  - name: Delete Moodle content & directory
    file:
      state: absent
      path: "{{ nginx_root_dir }}"

  - name: Create an empty Moodle www directory
    file:
      path: "{{ nginx_root_dir }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0755